
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: auth
    labels:
      app: auth
  spec:
    ports:
      - port: 8080
    selector:
      app: auth
    type: NodePort
- apiVersion: v1
  kind: Service
  metadata:
    name: ducky
    labels:
      app: ducky
  spec:
    ports:
      - port: 8080
    selector:
      app: ducky
    type: NodePort
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: auth
    labels:
      app: auth
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: auth
      spec:
          containers:
          - env:
              - name: JAEGER_HOST_PORT
                value: "192.168.99.100:30328"
              - name: JAEGER_SERVICE_NAME
                value: "Auth"
            image: sevteen/ducktracing-auth
            name: auth
            ports:
              - containerPort: 8080
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: ducky
    labels:
      app: ducky
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ducky
      spec:
          containers:
          - env:
              - name: JAEGER_AGENT_HOST_PORT
                value: "192.168.99.100:30328"
              - name: AUTH_HOST_PORT
                value: "${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}"  
            image: sevteen/ducktracing-ducky
            name: ducky
            ports:
              - containerPort: 8080